### ISSUE TITLE
Navigation menu section: Proper naming for the submenu items sample under 'Shipment Over $1000' menu.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#16]
![image](https://cloud.githubusercontent.com/assets/11186304/7128703/8e99e2da-e288-11e4-9bba-bf011cd6a8aa.png)

**Comment by rexcebudigital** [comment]
What should I put on the sub menu? I just followed the psd design. 

And the screenshot does not connect to the bug.

**Comment by maluzynel** [comment]
It's the 'lorem ipsum' submenu items under the 'Shipment over $1000' main menu but are now removed. This is fixed. I'm sorry for the incorrect screenshot.
