### ISSUE TITLE
Homepage - Leadins section below the banner section: Heading titles font family should be 'OpenSans Light'.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#20]
![image](https://cloud.githubusercontent.com/assets/11186304/7128788/daf54042-e289-11e4-9ca8-78d8ee27dfb7.png)

**Comment by rexcebudigital** [comment]
Its already an OpenSans Light Font, the Light refers to the font-weight: 300.
