### ISSUE TITLE
All pages - Content section: Heading titles main base H2 font size should be 34px as per design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#26]
![image](https://cloud.githubusercontent.com/assets/11186304/7129042/a216e678-e28d-11e4-86cf-85b7932a044d.png)

**Comment by rexcebudigital** [comment]
Its already set to 34px; proof: http://universalcustomsbrokers.local.titanweb.com.au/company-profile/
