### ISSUE TITLE
Homepage - Shipment under $1000 section: Row item without heading title should not be shown in the page.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#44]
![image](https://cloud.githubusercontent.com/assets/11186304/7153195/9ace250a-e37a-11e4-91a9-7cca6a46ef49.png)

**Comment by maluzynel** [comment]
'Shipment under $1000 services' custom fields is missing on home page at the backend.

**Comment by rexcebudigital** [comment]
Its in the Shipment under page at the backend.
