### ISSUE TITLE
Shipment over $1000 page - Sidebar section: Shipment Under $1000 section should be based from Leadins custom posts.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#65]
![image](https://cloud.githubusercontent.com/assets/11186304/7173581/943f6138-e42c-11e4-95ec-87866e64a0dc.png)

**Comment by rexcebudigital** [comment]
What do you mean based from leadins? Can you explain maore, thanks

**Comment by maluzynel** [comment]
This can be manageable at the backend, usually from Leadins custom posts since this is what exactly added on the leadins custom posts at the backend.

![image](https://cloud.githubusercontent.com/assets/11186304/7246395/47ccf62e-e82f-11e4-8f8f-b6d314dd8bd9.png)
