### ISSUE TITLE
Get a free quote link: Are we not going to implement a separate form for 'Ge a free quote' instead of 'Clearance Document' form?

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#66]
Affected:
Header section 'Get a free quote' button
Homepage content section 'Get a free quote' button
Inner pages sidebar 'Get a free quote' button

![image](https://cloud.githubusercontent.com/assets/11186304/7173659/96e8538a-e42d-11e4-8810-e49e688d9329.png)

**Comment by maluzynel** [comment]
Your answer is required to close this item.

**Comment by rexcebudigital** [comment]
I think No, there's no need for another quotation form by basing from the design brief, the proceed button under shipment under page is also a quote form. It will be a redundant form if we will create another one.
