### ISSUE TITLE
Shipment under $1000 page - Sidebar section: Shipment over $1000 section should be based from Leadins custom posts.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#71]
![image](https://cloud.githubusercontent.com/assets/11186304/7173822/203b19c2-e430-11e4-908a-43c33eec1310.png)

**Comment by rexcebudigital** [comment]
Same with the Shipment under. please can you explain more. Thanks

**Comment by maluzynel** [comment]
Refer to Issue #65
