### ISSUE TITLE
Clearance Document pop-up form: Formfields breaks in IE 7 browser.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#82]
![image](https://cloud.githubusercontent.com/assets/11186304/7175592/f4acf62c-e448-11e4-824f-f621777d8343.png)

**Comment by maluzynel** [comment]
Not yet fixed. Poper alignment of textfields and its default value.

![image](https://cloud.githubusercontent.com/assets/11186304/7246934/41ffdc64-e836-11e4-91e8-43b4c8b68b74.png)

**Comment by rexcebudigital** [comment]
I did not fix anything for this, please consider doing a hard refresh or clear your cache.
![screenshot](https://cloud.githubusercontent.com/assets/11186391/7250406/9b16c7ea-e854-11e4-891e-8e4f4fec99d2.jpg)

**Comment by maluzynel** [comment]
I have clear cached many times.

![image](https://cloud.githubusercontent.com/assets/11186304/7268937/fa0999d8-e900-11e4-9a4e-87b248577dc9.png)
