### ISSUE TITLE
Menu button: Unable to toggle up the dropdown menus in mobile devices view.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#87]
iTouch 5
Samsung S4

![image](https://cloud.githubusercontent.com/assets/11186304/7176077/9f548230-e44d-11e4-8dbc-0f2402adfec6.png)

**Comment by rexcebudigital** [comment]
I have tested the site using chrome developers tools, I don't see the error on samsung galaxy s4 on chrome dev tools, unfortunately we still dont have ipod devices here. Kindly do a clear cache. Thanks

**Comment by maluzynel** [comment]
Not yet fixed in iTouch mobile device. Menu button gets disappeared once the submenus are toggle down. Better to push down the toggle menus below the menu button. 
You can refer to this example: http://adrenalin-factory.stage.titanweb.com.au/
