### ISSUE TITLE
Homepage: Distorted section of 'Shipment over $1000' post items.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Universal-Customs-Brokers#90]
All mobile devices

![image](https://cloud.githubusercontent.com/assets/11186304/7176495/8a240756-e451-11e4-86a6-429b94dfdf6a.png)

**Comment by maluzynel** [comment]
Not yet fixed. Still truncated. Better to display horizontally with prev/next arrow buttons.

![image](https://cloud.githubusercontent.com/assets/11186304/7247096/ffb7cd06-e837-11e4-9199-35c8d2bc4f06.png)

**Comment by rexcebudigital** [comment]
Done. No need to display it by 1, and no need for arrows on mobile.
